#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59
# shellcheck disable=SC2034

# Loop through hours
hour=0
while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  
  # Loop through minutes for each hour
  minute=1
  while [ "$minute" -le 59 ]; do
    echo "$minute"
    minute=$((minute + 1))
  done
  
  hour=$((hour + 1))
done
