#!/bin/bash

# Use ps command with options:
# -e: select all processes
# -o: specify output format
# --forest: show process hierarchy

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
