#!/usr/bin/env bash
# Displays the PID and process name of processes containing the word "bash"

for pid in /proc/[0-9]*; do
    pid=${pid##*/}
    if [[ $(tr '\0' '\n' < /proc/$pid/cmdline | grep -i "bash") ]]; then
        echo "$pid $(tr '\0' '\n' < /proc/$pid/cmdline | head -n1)"
    fi
done
